"""empty message

Revision ID: 51b12a4c69ae
Revises: f7905b7d7221
Create Date: 2021-07-05 22:44:00.342293

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '51b12a4c69ae'
down_revision = 'f7905b7d7221'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tipousuario',
    sa.Column('idTipoUsuario', sa.Integer(), nullable=False),
    sa.Column('nombreTipo', sa.String(length=45), nullable=True),
    sa.Column('descripcion', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('idTipoUsuario')
    )
    op.create_table('usuario',
    sa.Column('idUsuario', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=45), nullable=True),
    sa.Column('apellido', sa.String(length=45), nullable=True),
    sa.Column('email', sa.String(length=55), nullable=True),
    sa.Column('password', sa.String(length=8), nullable=True),
    sa.Column('fkTipousuario', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['fkTipousuario'], ['tipousuario.idTipoUsuario'], ),
    sa.PrimaryKeyConstraint('idUsuario')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('usuario')
    op.drop_table('tipousuario')
    # ### end Alembic commands ###
