"""empty message

Revision ID: 67f4859ce97b
Revises: 1dc4859832bf
Create Date: 2021-07-06 11:30:20.167200

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '67f4859ce97b'
down_revision = '1dc4859832bf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tipousuario',
    sa.Column('idTipoUsuario', sa.Integer(), nullable=False),
    sa.Column('nombreTipo', sa.String(length=45), nullable=True),
    sa.Column('descripcion', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('idTipoUsuario')
    )
    op.create_table('usuario',
    sa.Column('idUsuario', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=45), nullable=True),
    sa.Column('apellido', sa.String(length=45), nullable=True),
    sa.Column('email', sa.String(length=55), nullable=True),
    sa.Column('password', sa.String(length=8), nullable=True),
    sa.Column('fkTipoUsuario', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['fkTipoUsuario'], ['tipousuario.idTipoUsuario'], ),
    sa.PrimaryKeyConstraint('idUsuario')
    )
    op.create_table('provedor',
    sa.Column('idProvedor', sa.Integer(), nullable=False),
    sa.Column('nombreprovedor', sa.String(length=70), nullable=True),
    sa.Column('telefono', sa.String(length=15), nullable=True),
    sa.Column('fkUsuario', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['fkUsuario'], ['usuario.idUsuario'], ),
    sa.PrimaryKeyConstraint('idProvedor')
    )
    op.create_table('ubicacion',
    sa.Column('idUbicacion', sa.Integer(), nullable=False),
    sa.Column('colonia', sa.String(length=45), nullable=True),
    sa.Column('calle', sa.String(length=45), nullable=True),
    sa.Column('estado', sa.String(length=55), nullable=True),
    sa.Column('codigopostal', sa.String(length=6), nullable=True),
    sa.Column('fkUsuario', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['fkUsuario'], ['usuario.idUsuario'], ),
    sa.PrimaryKeyConstraint('idUbicacion')
    )
    op.create_table('producto',
    sa.Column('idProducto', sa.Integer(), nullable=False),
    sa.Column('nombreProducto', sa.String(length=57), nullable=True),
    sa.Column('tipo', sa.String(length=38), nullable=True),
    sa.Column('precio', sa.String(length=3), nullable=True),
    sa.Column('foto', sa.String(length=48), nullable=True),
    sa.Column('fkProvedor', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['fkProvedor'], ['provedor.idProvedor'], ),
    sa.PrimaryKeyConstraint('idProducto')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('producto')
    op.drop_table('ubicacion')
    op.drop_table('provedor')
    op.drop_table('usuario')
    op.drop_table('tipousuario')
    # ### end Alembic commands ###
