"""empty message

Revision ID: f7905b7d7221
Revises: 09671c772f2e
Create Date: 2021-07-05 22:23:19.357806

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f7905b7d7221'
down_revision = '09671c772f2e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('usuario',
    sa.Column('idUsuario', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=45), nullable=True),
    sa.Column('apellido', sa.String(length=45), nullable=True),
    sa.Column('email', sa.String(length=55), nullable=True),
    sa.Column('password', sa.String(length=8), nullable=True),
    sa.PrimaryKeyConstraint('idUsuario')
    )
    op.add_column('tipo_usuario', sa.Column('idTipoUsuario', sa.Integer(), nullable=False))
    op.drop_column('tipo_usuario', 'id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tipo_usuario', sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False))
    op.drop_column('tipo_usuario', 'idTipoUsuario')
    op.drop_table('usuario')
    # ### end Alembic commands ###
